services:
  - type: web
    name: smartedubot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python smartedubot.py
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: WEBHOOK_URL
        sync: false
